### ISSUE TITLE
Warned player doesn't receive warn message

### ISSUE THREAD

**Issue by Twonox** [ruany/LiteBans#10]
Hi,

When we warn a player, he doesn't receive a warn notification.

Tested with latest version of LiteBans with BungeeCord.

**EDIT:** I've tested it in a simple server (without bungeecord) and the warn message is sent. So, the problem comes from the BungeeCord side of LiteBans.

**Comment by ruany** [comment]
litebans.notify.warned: Permission to see own warning notifications. True by default under Spigot.
litebans.notify.muted: Permission to see own muted notifications. True by default under Spigot.

BungeeCord doesn't have a system to grant default permissions as with plugin.yml AFAIK, so these have to be defined manually.

Cannot replicate.
