### ISSUE TITLE
Warn broadcas--issue with $player variable

### ISSUE THREAD

**Issue by Twonox** [ruany/LiteBans#11]
In
```
warn:
    broadcast: ''
```

The executor is in `$player` variable

I mean, if I warn a player, it say that for example: "Twonox warned Twonox" instead of "Twonox  warned PlayerX"

**Comment by ruany** [comment]
Use $warnedPlayer

Player variables are not available in broadcasts because the target is not always a player, it can be an IP address with no name attached to it.
