### ISSUE TITLE
Global warn delay

### ISSUE THREAD

**Issue by Twonox** [ruany/LiteBans#15]
Hi,

Currently there is a cooldown option to don't warn the same player per staff.
The staff's rules of my server says "Don't warn again a player who has been warned today". So, to apply correctly that, I need an option to set a global warn cooldown per player.
- If the global cooldown option is set to 6 hours, the staff B can't warn the player A if the Staff A has warned the player A 3 hours ago, but the staff C can warn player A if the staff A has warned player A 7 hours ago.

**Comment by ruany** [comment]
The warning cooldown is per-player, not per-staff.

This is the logic in pseudocode:
```
on warn:
 warning = get last warning (warned player)
 if (warning is active) and (time since warning <= cooldown):
  cancel warn
```
