### ISSUE TITLE
Offline UUID's

### ISSUE THREAD

**Issue by SeDark** [ruany/LiteBans#20]
I have a problem with the uuid's offline

On my server I use the "FastLogin" plugin, so I have both uuid's premium and non-premium
I am trying to use the api of visage.surgeplay.com, but this one needs the non-premium uuid to display skin, if it does not work correctly.

The problem is that non-premium users do not get the uuid if not the username

In settings.php (litebans interface)

$this->avatar_source = 'https://visage.surgeplay.com/head/50/$UUID';

But non-premium users get the username, not the uuid and so it does not work

Is there any solution?

Thx

**Comment by ruany** [comment]
Added an option https://github.com/ruany/litebans-php/commit/531aa2c6d536daf0a48911e26b2ce2a7af7e1882
