### ISSUE TITLE
Option to hide or use alternative disconnect reason from console.

### ISSUE THREAD

**Issue by mibby** [ruany/LiteBans#27]
LiteBans 2.2.4

```
  # Log all notifications to the console?
  notify_console: false
```

Would it be possible to hide the disconnect reason from console or have a secondary alternative message solely for console when a player is kicked / banned and tries to login? With a heavily tweaked config, players being disconnected for various reasons can take up quite a lot of console chat lines and be spammy.

```
[16:50:14] [Server thread/INFO]: staff issued server command: /tempban player 3s test
[16:50:14] [Server thread/INFO]: player lost connection: -------------------------------------------
Your account has been suspended from server!

Reason » test
Banned on » 2017-10-13
Banned by » staff
Duration » 2 seconds

You may appeal at site.com/appeal.
-------------------------------------------
[16:50:14] [Server thread/INFO]: [-] player has left the server.
[16:50:14] [Server thread/WARN]: handleDisconnection() called twice
```

```
[16:49:24] [User Authenticator #105/INFO]: Disconnecting com.mojang.authlib.GameProfile@64e1e3b1[id=d6ced541-214e-463f-a818-3ac184ab644a,name=player,properties={textures=[com.mojang.authlib.properties.Property@2b1b0299]},legacy=false] (/ip:port): You are banned from this server!

Banned on: 2017-10-13
Banned by: ~staff
Reason: you suck

You are permanently banned!
Appeal at: http://example.com
[16:49:24] [Server thread/INFO]: com.mojang.authlib.GameProfile@64e1e3b1[id=d6ced541-214e-463f-a818-3ac184ab644a,name=player,properties={textures=[com.mojang.authlib.properties.Property@2b1b0299]},legacy=false] (/ip:port) lost connection: You are banned from this server!

Banned on: 2017-10-13
Banned by: ~staff
Reason: you suck

You are permanently banned!
Appeal at: http://example.com
```

**Comment by ruany** [comment]
These lines are outputted to the console by the Minecraft server itself, not by LiteBans.

In order for LiteBans to override this message, it would have to either:
- Override the net.minecraft.server.LoginListener directly (I'd have to make sure my code is compatible with all net.minecraft.server versions from 1.7.10 to 1.12.2, and future versions, otherwise it will break)
- Hook into the logging system (this is prone to failure if there are other plugins doing this)

I don't like either of these approaches. In any case, it's not "nice" for a banning system to override a core function of the Minecraft server like this, and no other plugins accomplish this, to my knowledge.

**Comment by mibby** [comment]
If a player is kicked from Bungee directly, wouldn't it still report to the server the disconnect reason?

What is the best way to go about installing LiteBans on BungeeCord while keeping it installed on both Bukkit servers (using a shared database) for permission and command handling?

**Comment by ruany** [comment]
> If a player is kicked from Bungee directly, wouldn't it still report to the server the disconnect reason?
Nope, the servers behind Bungee aren't contacted or notified if someone can't join the proxy, it occurs on a higher layer.

> What is the best way to go about installing LiteBans on BungeeCord while keeping it installed on both Bukkit servers (using a shared database) for permission and command handling?
If the plugin is installed on BungeeCord, you'll have to use BungeeCord permissions (e.g. BungeePerms or BungeePEXBridge)
The best way would be to drop it in the BungeeCord plugins folder and connect it to the same database. I'm not aware of any better ways to do this.

**Comment by mibby** [comment]
> Nope, the servers behind Bungee aren't contacted or notified if someone can't join the proxy, it occurs on a higher layer.

But you are still disconnecting the user connection that was forwarded onto a specific server. I'm guessing the server would just output in console that the user disconnected or timed out then rather than provide the disconnect reason.

> The best way would be to drop it in the BungeeCord plugins folder and connect it to the same database.
I'm not aware of any better ways to do this.

It isn't possible to continue handling commands and permissions on the server-side LiteBans instance and just forward the disconnect processing to the Bungee instance via plugin message channels for direct Bungee kicking?

**Comment by ruany** [comment]
> But you are still disconnecting the user connection that was forwarded onto a specific server. I'm guessing the server would just output in console that the user disconnected or timed out then rather than provide the disconnect reason.

The player is disconnected before the proxy can decide to forward the connection.

>It isn't possible to continue handling commands and permissions on the server-side LiteBans instance and just forward the disconnect processing to the Bungee instance via plugin message channels for direct Bungee kicking?

Actually, there is a "bungeecord" option in config.yml which makes the proxy kick the player through a plugin messaging channel, I'm not sure if it would help here.

**Comment by ruany** [comment]
The "bungeecord" option in config.yml only applies to kicks (i.e. on command), not disconnects (on join), though.

**Comment by mibby** [comment]
> The player is disconnected before the proxy can decide to forward the connection.

However it would still send a disconnect message when kicking or banning someone that is online.

> Actually, there is a "bungeecord" option in config.yml which makes the proxy kick the player through a plugin messaging channel, I'm not sure if it would help here.

Assuming LiteBans communicates between Bukkit and Bungee instances to forward the disconnect to Bungee's LiteBans to kick a player, that would probably eliminate the issue.

**Comment by ruany** [comment]
Problem is, the plugin messaging channel can only be used to kick players who have already connected to the server.

Players are being disconnected before they can connect, plugin messaging channels are useless here.

**Comment by mibby** [comment]
Right. So if I had LiteBans on BungeeCord, it would disconnect players who are banned when they try to login from the proxy end before the connection ever makes it to a server. If I had LiteBans "bungeecord" option set on bukkit, it would forward the kick message to Bungee to kick players from the Bungee instance rather than bukkit?

**Comment by ruany** [comment]
Yup.

**Comment by mibby** [comment]
And I'm assuming with LiteBans still installed on Bukkit, commands and permissions would still be checked on that individual server when typing? Or does enabling bungee disable all that?

**Comment by ruany** [comment]
The bungeecord option has absolutely no other effects, it only changes the way that LiteBans kicks online players.

**Comment by mibby** [comment]
Great. I'll enable it and install LiteBans on Bungee. Hopefully the kick disconnect message still isn't outputted on the Bukkit instance.

**Comment by ruany** [comment]
Note, that option doesn't require LiteBans to be installed under BungeeCord, it sends a plugin message handled by the proxy itself.

**Comment by mibby** [comment]
Oh really? So I just need LiteBans installed on both bukkit servers with the Bungee setting enabled then?

**Comment by ruany** [comment]
Yes.

**Comment by mibby** [comment]
> The bungeecord option has absolutely no other effects, it only changes the way that LiteBans kicks online players.

I assume I'd still want LiteBans on BungeeCord itself to disconnect players from the proxy level rather than have it attempt to forward the connection and then kicked with the ban reason though, right?

So install on Bungee to prevent the connection ever making it past Bungee if banned and change the bungee config setting on bukkit to true to kick players from the proxy directly.

**Comment by mibby** [comment]
Upon testing, turns out that you can't have LiteBans installed on Bungee and Bukkit to allow server based permissions to still work. Bungee overrides and outputs ```You don't have permission!```.  

Since bungeecord set to true in the config only handles online kicking and the disconnect reason still shows up on the individual server when trying to login banned, guess I'm out of options.
