### ISSUE TITLE
$dateStart date off by one.

### ISSUE THREAD

**Issue by mibby** [ruany/LiteBans#30]
LiteBans v2.2.3

Banned an account on 10/21 for testing. Upon logging in, the date specified showed yesterday. Server clock is synced and shows the correct date, so the variable seems to be off by one.
![link](https://i.imgur.com/RHdCIiF.png)
```
banned_message_base: |-
  &8&m-------------------------------------------
  &fYour account has been suspended from address!

  &fReason &8» &6$reason
  &fBanned on &8» &6$dateStart
  &fBanned by &8» &6$executor

  &fYou may appeal at &baddressl&f.
  &8&m-------------------------------------------
```

**Comment by ruany** [comment]
This is likely a timezone issue.

- If `use_timezone` is enabled in config.yml, the plugin will offset dates by the system's timezone
- If `use_database_time` is enabled in config.yml, the plugin will use UTC+0.

**Comment by mibby** [comment]
```
# If enabled, LiteBans will use the database server's time rather than the system time.
use_database_time: false
# If enabled, the local system timezone will be used.
# UTC time will be stored in the database, but dates will be formatted using the timezone offset.
use_timezone: true
```

I'm guessing the UTC timezone stored is wrong? Server time should be set to LA / PDT.

**Comment by ruany** [comment]
System time should be synchronized to UTC+0 using NTP. The system timezone is separate from that.
You can add "HH:mm" to the end of time_format in messages.yml to see the exact time.

**Comment by mibby** [comment]
Ah, I see.

Changing it to the following does seem to resolve the issue for me. Thanks for the info.
```
# If enabled, LiteBans will use the database server's time rather than the system time.
use_database_time: true
# If enabled, the local system timezone will be used.
# UTC time will be stored in the database, but dates will be formatted using the timezone offset.
use_timezone: false
```
