### ISSUE TITLE
Kicking players is name specific.

### ISSUE THREAD

**Issue by mibby** [ruany/LiteBans#32]
A player is named iMxFolly.
You want to kick him so you type ```/kick folly```.
LiteBans outputs ```Player folly is not online on this server. Cross-server kick has been requested.```
iMxFolly is not kicked.

Would it be possible to add an option to rely on some form of heuristics to kick players by their partial name, as well as also support kicking them by their displayname nickname?

**Comment by ruany** [comment]
There are 5 players on 5 different servers, one is named folly1, another is named folly2, another is named folly3...
Which one is kicked? All of them, one of them (at random?), or none of them?

Probably none of them, this should output an error. That would require a round-trip query to every single server connected to the same database, asking them whether they have a matching player online before proceeding to kick the player.
That would work, but it's too much effort to rewrite the entire method for a simple feature like this that you can already achieve by installing the plugin under BungeeCord.

**Comment by mibby** [comment]
If I installed the plugin on BungeeCord, I then wouldn't be able to make use of display names in messages since that is defined per spigot side. Especially since my permissions are delegated individually per server instead of Bungee globally, I also wouldn't have access to commands.

With Essentials (since it supports partial name finding and displayname kicking), I believe it kicks the first person it matches with. I personally find this behavior to be fine the rest of my team prefers it since most of the time, you would specify enough characters to fully match a player you intended to kick. Someone with the same partial name online is a bit uncommon. 

Surely it can't be too hard to implement and have an option to opt in? As it opens up the command to be less restrictive and easier for staff to pick players by the names they are known for.
https://github.com/drtshock/Essentials/blob/bbe0ca93024512257e79917f0bd4f1710a1bf229/Essentials/src/com/earth2me/essentials/commands/Commandkick.java#L43

**Comment by ruany** [comment]
Essentials doesn't do cross-server kicking.
If I simply added name matching to the existing method, all servers would attempt to match one player, and possibly more than one player would be kicked if there was more than one match.

**Comment by mibby** [comment]
> Essentials doesn't do cross-server kicking.

I know, hence why I switched over to LiteBans. 

> If I simply added name matching to the existing method, all servers would attempt to match one player, and possibly more than one player would be kicked if there was more than one match.

You could add it as a new setting that defaults to false for old behavior to keep consistency between servers upgrading and only kick the first person it matches with if it matches multiple people. Just having the freedom to ban & kick players by their displayname and partial names opens up functionality quite a bit.
