### ISSUE TITLE
Anyway to remove expired bans from banlist PHP website?

### ISSUE THREAD

**Issue by darknight99x** [ruany/LiteBans#33]
HI, I was wondering if there is a command that I can put in a scheduled task to remove expired bans or something from the list, it's gets cluttered and I only wish to see bans that are active.

**Comment by ruany** [comment]
https://github.com/ruany/litebans-php/blob/master/inc/settings.php#L32

**Comment by darknight99x** [comment]
Apologies I am new to this plugin, thanks!
