### ISSUE TITLE
tempban_max affecting full ban time length.

### ISSUE THREAD

**Issue by mibby** [ruany/LiteBans#34]
LiteBans v2.2.4

The tempban max duration seems to affect full bans. Staff who full ban players, the ban turns into a temp-ban one.

```
[19:04:30] [Server thread/INFO]: player issued server command: /ban player2 test
```

When player2 tries to login, it says they have 7 days until their ban expires. As well as the web panel displays when their ban will expire.

```
durations:
  # Can be bypassed with the permission "litebans.unlimited.ban"
  tempban_max: 7 days
```

I understand it is probably because the ban and tempban commands are the same command. But this doesn't make sense since you have separate permissions for banning and temp-banning. I interpreted as you could allow staff to either full ban someone or temp-ban someone with a forced upper limit to avoid a temp-ban of 3 years for example.

**Comment by ruany** [comment]
In config.yml:
```
durations:
  ...
  # If true, players will not get an error when using a duration higher than the configured limit.
  # The duration will be rounded down to the maximum duration instead.
  round_down: true
```

**Comment by ruany** [comment]
* Having litebans.ban also grants litebans.tempban
* Having either of these does not give you litebans.unlimited
* /ban and /tempban are the exact same command, /tempban only requires a duration, nothing more. Same with /tempmute.

**Comment by mibby** [comment]
So it isn't possible to give people the ability to full ban & temp-ban with an upper maximum limit on temp-bans?

**Comment by ruany** [comment]
Not sure if you were the one to report it over Discord, but if you weren't: this is only a bug with the messages, the durations are rounded down properly but the permanent-duration messages are used for broadcasts in this case. This will be fixed next release.
