### ISSUE TITLE
Bug With Commands

### ISSUE THREAD

**Issue by AirCraze** [ruany/LiteBans#36]
banip works (maybe idk)
but when I use it 2 times it says removed the last ban for %name%
if i try it again
it says the same thing over and over
and I found other commands that dont work I forgot what it was, but you can check it.
I also cant find any error on the console

server version: 1.8
plugin version: latest

**Comment by ruany** [comment]
Please provide the full command you're using, including arguments.
If you use "/ipban -u" ... you will unban the target.

> and I found other commands that dont work I forgot what it was, but you can check it.
I've "checked it". I don't upload completely broken releases of the plugin, every version is tested. Everything works as expected.

**Comment by ruany** [comment]
That doesn't happen for me or for anyone else.
