### ISSUE TITLE
No Permission!

### ISSUE THREAD

**Issue by DarkPotato23** [ruany/LiteBans#37]
I'm not sure why.. It was working fine before then all of a sudden I was testing everything and it said I don't have permission when I try to do the litebans cmd /ban [Name]

I'm not sure why this isn't working, I have looked at my permissions plugin. The Plugin Litebans loads just fine, the only real reason is it wont let me do /ban.. I'm OP on the server aswell as the others and I have given myself the litebans.* permission node and restarted the server multiple times...

Regards to the best ban plugin I have ever had!

Melon Nation Developer

Dark_Potato23

**Comment by ruany** [comment]
https://github.com/ruany/LiteBans/wiki/FAQ#q-permissions-are-not-working--commands-arent-working-properly
