### ISSUE TITLE
Warning does not work!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by AirCraze** [ruany/LiteBans#39]
When i do the warnings 3 times
it says PLAYER NOT FOUND
for kick 
BUT ban does work after the 4th warning

Please join my discord: https://discord.gg/4ugfTRE
so you can talk to me.

**Comment by ruany** [comment]
Offline players cannot be kicked. Not a bug.
Please provide more useful information if you want me to pay any attention to any issues you create.
