### ISSUE TITLE
/hist on Bungeecord

### ISSUE THREAD

**Issue by Untuned** [ruany/LiteBans#4]
When using Litebans on Spigot, there is a /hist shortcut for /history.  On bungeecord, there is not.  No command found for it either.

**Comment by ruany** [comment]
Known issue. Aliases won't be added until there's a way to disable commands, otherwise the plugin could override commands from other plugins and there wouldn't be a way to prevent that.

For now you can use a command alias plugin if /hist is important to you.

**Comment by Untuned** [comment]
Any recommendations for one I should use?

**Comment by ruany** [comment]
https://www.spigotmc.org/resources/commandcontrol.76/

**Comment by Untuned** [comment]
Thanks, I'm sure this will help.
