### ISSUE TITLE
WARNINGS DONT WORK (LATEST VERSION)

### ISSUE THREAD

**Issue by AirCraze** [ruany/LiteBans#40]
When i do the warnings 3 times
it says PLAYER NOT FOUND
for kick
BUT ban does work after the 4th warning

Please join my discord: https://discord.gg/4ugfTRE
so you can talk to me.

https://i.imgur.com/IcW2MUf.png

**Comment by AirCraze** [comment]
ruany PLEASE HELP ME :(

**Comment by ruany** [comment]
If you open a new issue every single time you want to complain over a non-existent problem I will just ignore you, block you and close all of your issues, because you are abusing the system.
