### ISSUE TITLE
Excluding a server

### ISSUE THREAD

**Issue by KaizerZen** [ruany/LiteBans#42]
Hi, so I'm running a BungeeCord Network and we have our main servers and some forced hosts that are for friends or other things.

So when we ban someone from the lobby server it also gets banned on our private server. Is there a config option to exclude servers or make the bans only affect, lets say, 3 servers?

**Comment by ruany** [comment]
If you want per-server bans to only affect a certain set of servers, you either have to create individual bans for each server in the set, or set all of those servers to have the same server_name (Spigot only) which will prevent individual server bans, but will allow bans to affect all servers with the same name.

I'm considering a server-group option though that would require a bit of extra query overhead for every group that a server is in, and bans would still only be able to affect one group of servers even with this option.

**Comment by KaizerZen** [comment]
So if I'm running BungeeCord there isnt a workaround?

**Comment by ruany** [comment]
If the plugin is installed in the BungeeCord plugins folder, no. Server names under BungeeCord are defined under the "servers" list in BungeeCord's config.yml and those servers can't have the same name, but LiteBans is fine with its own instances sharing the same server name under Spigot.

**Comment by KaizerZen** [comment]
I think I'll move LiteBans to Spigot.
Any recommendations or tips?

**Comment by KaizerZen** [comment]
Alright thanks
