### ISSUE TITLE
Warning a player never reaches the player

### ISSUE THREAD

**Issue by x1p** [ruany/LiteBans#44]
We noticed that a warning never reaches the player misbehaving.
Staff can see the broadcast of the player being warned.
Used litebans 2.2.9 & 2.2.12.

**Comment by ruany** [comment]
Cannot replicate.

These permissions are true by default under Spigot, but require manual configuration under BungeeCord:
* litebans.notify.broadcast: Permission to see ban/mute/warning/kick broadcasts.
* litebans.notify.warned: Permission to see own warning notifications.
* litebans.notify.muted: Permission to see own muted notifications.

**Comment by ruany** [comment]
Closing unless issue can be replicated.
