### ISSUE TITLE
Id of a ban

### ISSUE THREAD

**Issue by FrankHeijden** [ruany/LiteBans#45]
Hey,

Could you make a feature which makes a ban ID of like 4 characters (a-Z,0-9) randomly so we can display that in the ban message & lookup it through a command like /lookup <ID>?

Makes it easier for banned player to open an appeal and for staff to lookup the ban.

**Comment by ruany** [comment]
There is an "$id" variable in messages.yml. The ID can be used to lookup bans on the web interface.
