### ISSUE TITLE
WordPress

### ISSUE THREAD

**Issue by kajahofman** [ruany/LiteBans#49]
Hello,
I have WordPress on my website, but I don't know how to install the web plugin. Can you help me? Thanks.

**Comment by ruany** [comment]
The web interface is not a plugin and has absolutely nothing to do with WordPress.

It must be installed separately.

https://github.com/ruany/litebans-php/wiki/Installation

**Comment by kajahofman** [comment]
Ok, And do you have some time to create that plugin?

**Comment by ruany** [comment]
Nope. Not going to happen.
