### ISSUE TITLE
Mute broadcast message

### ISSUE THREAD

**Issue by CraftedStone16** [ruany/LiteBans#5]
When I went to change a mute broadcast it was not working. It would show that it is working to my layout design in the messages.yml but when I reloaded it in the server and then when I try to mute it has the default layout mute message still and it didn't break the config either. Is there a possible chance that its not Bungeecord Supported and only Spigot and Bukkit becuase i have it running through bungeecord! Overall this is a very great ban/punish managing plugin i really did spend my money wisely and worthly.

**Comment by Untuned** [comment]
Could you send the messages.yml file here? (put it in a gist)

**Comment by ruany** [comment]
The plugin does support BungeeCord completely, you've most likely made a mistake somewhere while editing the configuration.

Are there any errors shown in the console?

If you paste your configuration here or in PM I'll check it myself and fix it for you if necessary.

**Comment by CraftedStone16** [comment]
https://gist.github.com/CraftedStone16/9e0bb2c18315fa1e5588f58ec023f3c7 this is my messages.yml, everything works except for the mute broadcast message. And all the broadcast messages are the same exact layout type but the only one that does not work mute.

**Comment by ruany** [comment]
Works for me:

```
>mute test
[20:42:03 INFO]: [----------[Mute]----------]
Staff: Console
Player: test
Reason: Spamming
[----------[Mute]----------]
```

**Comment by CraftedStone16** [comment]
I don't understand why it won't for me

**Comment by CraftedStone16** [comment]
I'll check my console when I'm doing it

**Comment by CraftedStone16** [comment]
So I just tried it again and now it's working fine. So I don't understand what it was but it's now working
