### ISSUE TITLE
Lockdown bypass doesn't work

### ISSUE THREAD

**Issue by Twonox** [ruany/LiteBans#8]
Hi,

When activate the lockdown in my network (with litebans in bungeecord), I can't join it.
I use the permission `'*'` with the bungee plugin PowerFulPerms, additionally the permission `litebans.lockdown.bypass`, but I can't join the network.

LiteBans version: latest release
BungeeCord version: build 1250

**Comment by ruany** [comment]
Fixed in 2.2.4
https://www.spigotmc.org/resources/litebans.3715/update?update=174776
